### ISSUE TITLE
Add pol.

### ISSUE THREAD

**Issue by em-fong** [drewrwilson/toolsforactivism#39]
hey guys!

i'm fairly new to open source and am sort of exploring its implications, but am excited to help out any way i can especially regarding political engagement & activism! i found this tool that might be helpful to add to the readme: http://pol-itics.com/

**Comment by drewrwilson** [comment]
@em-fong this looks neat. thanks for sharing it!

**Comment by drewrwilson** [comment]
after poking around, it looks like their tool isn't available any more :( maybe it was a 2016 election related project?
